name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
jobs:
  cpp:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache ROOT build directory
        id: cache-root
        uses: actions/cache@v4
        with:
          path: ${{github.workspace}}/root_install
          key: ${{runner.os}}-root
      - name: Build ROOT from scratch without cache
        if: steps.cache-root.outputs.cache-hit != 'true'
        run: |
          git clone --branch latest-stable --depth=1 https://github.com/root-project/root.git root_src
          mkdir root_build  && cd root_build
          cmake -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/root_install ../root_src  -Dfitsio=OFF -Dgeometry=OFF -Dmysql=OFF -Dvdt=OFF  -DCMAKE_CXX_STANDARD=20 -Dclad=OFF -Dxrootd=OFF  -Dx11=OFF -Dxml=OFF -Dwebgui=OFF -Droot7=OFF -Drootfit=OFF -Dmysql=OFF -Dasimage=OFF -Dhttp=OFF -Dpgsql=OFF -Dtmva=OFF
          cmake --build . -- install -j10
      - name: Save ROOT build directory to cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: ${{github.workspace}}/root_install
          key: ${{runner.os}}-root
      - name: Update submodules
        run: git submodule update --init --recursive
      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.30.0'
      - name: Build and test
        run: |
          source ${{github.workspace}}/root_install/bin/thisroot.sh
          cmake -S . -B build -DWITH_TEST=ON
          cmake --build build -j 5
          cmake --install build --prefix install
          cd build && ctest --extra-verbose --output-on-failure
